
// This file is generated by ResourceLoader, do not edit it manually
// Generated from /home/antlion/Game_Jams/2_5D_game/resources
// Generated on 2024-01-10 13:08

#pragma once

#include <string>
#include <memory>

#include <SFML/Graphics/Texture.hpp>
#include <SFML/Audio/SoundBuffer.hpp>
#include <SFML/Audio/Music.hpp>

namespace Resources {

} // namespace Resources
